sudo: required
language: node_js
node_js:
  - "9.5.0"
services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - export PROJECT_DIR=$PWD
  - cd $PROJECT_DIR/logstash
  - ./build.sh
  - cd $PROJECT_DIR/postgres
  - ./build.sh
