version: '3'

services:
    app:
      build: ./app
      links:
        - postgres
      expose:
        - "8080"
      volumes:
        - ./app/:/src
      environment:
        - API_ENDPOINT=//localhost:8080/api
        - NODE_ENV=development
        - LOG_LEVEL=info

    api:
      build: ./api
      links:
        - postgres
      expose:
        - "8080"
      volumes:
        - ./api/:/src
      environment:
        - NODE_ENV=development
        - LOG_LEVEL=info
        - PORT=8080
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_NAME=statuscheck
        - DB_DIALECT=postgres
        - DB_HOST=postgres
      env_file: ~/status-check.env

    scheduler:
      build: ./scheduler
      links:
        - postgres
      volumes:
        - ./scheduler/:/src
      environment:
        - NODE_ENV=development
        - LOG_LEVEL=info
      env_file: ~/status-check.env

    nginx:
      build: ./nginx
      links:
        - app
        - api
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "8080:80"

    postgres:
      build: ./postgres
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - DB_NAME=statuscheck
        - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
