version: '3'

services:
    app:
      build: ./app
      links:
        - redis
      expose:
        - "8080"
      volumes:
        - ./app/:/src
      environment:
        - API_ENDPOINT=//localhost:8080/api
        - NODE_ENV=development

    api:
      build: ./api
      links:
        - redis
      expose:
        - "8080"
      volumes:
        - ./api/:/src
      environment:
        - NODE_ENV=development
      env_file: ~/status-check.env

    scheduler:
      build: ./scheduler
      links:
        - redis
      volumes:
        - ./scheduler/:/src
      environment:
        - NODE_ENV=development
      env_file: ~/status-check.env

    redis:
      image: redis
      ports:
          - "6379"

    nginx:
      build: ./nginx
      links:
        - app
        - api
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "8080:80"
