version: '3'

services:
  postgres:
    image: sflpro/status-check-postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      replicas: 1

volumes:
  pgdata:
    driver: local
