version: '3.1'

services:
  postgres:
    image: sflpro/status-check-postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - DB_NAME=statuscheck
      - PGDATA=/var/lib/postgresql/data/pgdata
    secrets:
      - postgres_password
    deploy:
      replicas: 1

  scheduler:
    image: sflpro/status-check-scheduler:latest
    environment:
      - API_ENDPOINT=http://api:8080/api
      - REQUEST_EMPLOYEES_INTERVAL=100000
      - REQUEST_TRANSACTIONS_INTERVAL=86400000
      - REQUEST_FROM=3
      - REQUEST_TO=1
      - TIMECARD_HOST_FILE=/run/secrets/timecard_host
      - TIMECARD_PATH_FILE=/run/secrets/timecard_path
      - TIMECARD_USER_FILE=/run/secrets/timecard_user
      - TIMECARD_PASS_FILE=/run/secrets/timecard_pass
    secrets:
      - timecard_host
      - timecard_path
      - timecard_user
      - timecard_pass
    deploy:
      replicas: 1

secrets:
  postgres_password:
    file: postgres_password.txt
  timecard_host:
    file: timecard_host.txt
  timecard_path:
    file: timecard_path.txt
  timecard_user:
    file: timecard_user.txt
  timecard_pass:
    file: timecard_pass.txt
volumes:
  pgdata:
    driver: local
