version: '3.1'

services:
  postgres:
    image: sflpro/status-check-postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=/run/secrets/postgres_user
      - POSTGRES_PASSWORD=/run/secrets/postgres_password
      - DB_NAME=/run/secrets/db_name
      - PGDATA=/var/lib/postgresql/data/pgdata
    secrets:
      - postgres_user
      - postgres_password
      - db_name
    deploy:
      replicas: 1

  scheduler:
    images: sflpro/status-check-scheduler:latest
    environment:
      - API_ENDPOINT=http://api:8080/api
      - REQUEST_INTERVAL=100000
      - REQUEST_FROM=3
      - REQUEST_TO=1
      - TIMECARD_HOST=/run/secrets/timecard_host
      - TIMECARD_PATH=/run/secrets/timecard_path
      - TIMECARD_USER=/run/secrets/timecard_user
      - TIMECARD_PASS=/run/secrets/timecard_pass
    secrets:
      - timecard_host
      - timecard_path
      - timecard_user
      - timecard_pass
    deploy:
      replicas: 1

secrets:
  postgres_user:
    file: postgres_user.txt
  postgres_password:
    file: postgres_password.txt
  db_name:
    file: db_name.txt
  timecard_host:
    file: timecard_host.txt
  timecard_path:
    file: timecard_path.txt
  timecard_user:
    file: timecard_user.txt
  timecard_pass:
    file: timecard_pass.txt
volumes:
  pgdata:
    driver: local
